import { useEffect, useMemo, useState } from 'react';
import { catalogLocations } from '../data/catalog';
import { districts, type Category, type Location } from '../data';
import { createCity } from '../city';
import { SearchPanel, useCatalogSearch } from './SearchPanel';

const categories: Array<{name: Category; icon: string}> = [{name:'Food & Drink',icon:'✦'},{name:'Nightlife',icon:'◒'},{name:'Culture',icon:'▣'},{name:'Shopping',icon:'◇'},{name:'Stay',icon:'⌂'},{name:'Services',icon:'＋'},{name:'Transport',icon:'↗'}];
export default function MapExperience(){
 const [query,setQuery]=useState(''),[category,setCategory]=useState<Category|'ALL'>('ALL'),[district,setDistrict]=useState('ALL'),[selected,setSelected]=useState<Location|null>(catalogLocations[0]),[night,setNight]=useState(false),[route,setRoute]=useState(false),[layers,setLayers]=useState<Record<string,boolean>>({City:true,Businesses:true,Nightlife:true});
 const filtered=useCatalogSearch(query,category,district); const mount=useMemo(()=>({current:null as HTMLDivElement|null}),[]); const [city,setCity]=useState<ReturnType<typeof createCity>|null>(null);
 useEffect(()=>{if(!mount.current)return;const instance=createCity(loc=>{setSelected(loc);instance.focus(loc)});setCity(instance);mount.current.appendChild(instance.renderer.domElement);const resize=()=>{if(!mount.current)return;instance.renderer.setSize(mount.current.clientWidth,mount.current.clientHeight,false);instance.camera.aspect=mount.current.clientWidth/mount.current.clientHeight;instance.camera.updateProjectionMatrix()};resize();window.addEventListener('resize',resize);let raf=0;const animate=()=>{raf=requestAnimationFrame(animate);instance.renderer.render(instance.scene,instance.camera)};animate();return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);mount.current?.removeChild(instance.renderer.domElement);};},[]);
 useEffect(()=>{city?.setNight(night)},[city,night]); const focus=(location:Location)=>{setSelected(location);city?.focus(location)}; const toggleLayer=(name:string)=>{const value=!layers[name];setLayers({...layers,[name]:value});city?.setLayer(name,value)};
 return <main className={night?'app night':'app'}><div className="map" ref={node=>{mount.current=node}}/><header className="topbar"><div className="brand"><span className="mark">✦</span><div><strong>SAINT MERIDIAN</strong><small>CITY ATLAS / LIVE CARTOGRAPHY</small></div></div><button className="icon-btn" onClick={()=>setNight(!night)}>{night?'☼':'◐'}</button></header><SearchPanel query={query} setQuery={setQuery} results={filtered} onSelect={focus}/><aside className="left-rail"><div className="eyebrow">MAP LAYERS</div>{['City','Businesses','Nightlife'].map(name=><button className={layers[name]?'layer active':'layer'} onClick={()=>toggleLayer(name)} key={name}><i className="layer-dot"/>{name}<span>{name==='Businesses'?catalogLocations.length:name==='Nightlife'?catalogLocations.filter(x=>x.category==='Nightlife').length:'ON'}</span></button>)}<div className="rail-rule"/><div className="eyebrow">DISTRICT FOCUS</div><select value={district} onChange={e=>{setDistrict(e.target.value);const d=districts.find(x=>x.name===e.target.value);if(d)city?.focus(d)}}><option value="ALL">All districts</option>{districts.map(d=><option key={d.name}>{d.name}</option>)}</select></aside><section className="filter-panel"><div className="eyebrow">DISCOVER / {filtered.length} PLACES</div><div className="chips">{categories.map(c=><button className={category===c.name?'chip selected':'chip'} onClick={()=>setCategory(category===c.name?'ALL':c.name)} key={c.name}><span>{c.icon}</span>{c.name}</button>)}</div></section>{selected&&<aside className="detail"><div className="detail-head"><span className="type">{selected.category.toUpperCase()}</span><button onClick={()=>setSelected(null)}>×</button></div><h1>{selected.name}</h1><div className="rating">★ {selected.rating}<span className="open">● OPEN NOW</span></div><p>{selected.description}</p><div className="info-row"><span>⌖</span><div><small>ADDRESS</small><strong>{selected.address}</strong></div></div><div className="info-row"><span>◈</span><div><small>DISTRICT</small><strong>{selected.district}</strong></div></div><button className="route" onClick={()=>{setRoute(true);city?.setRoute({x:0,z:0},selected)}}>{route?'✓ ROUTE DRAWN TO LOCATION':'↗ DRAW ROUTE TO HERE'}</button></aside>}<div className="district-tag"><span className="pulse"/>{selected?.district??'MERIDIAN CORE'}<small>{catalogLocations.length} POIs</small></div></main>;
}
