import { useEffect, useMemo, useRef, useState } from 'react';
import { createCity } from './city';
import { districts, locations, type Category, type Location } from './data';

const categories: Array<{name: Category; icon: string}> = [{name:'Food & Drink',icon:'✦'},{name:'Nightlife',icon:'◒'},{name:'Culture',icon:'▣'},{name:'Shopping',icon:'◇'},{name:'Stay',icon:'⌂'},{name:'Services',icon:'＋'},{name:'Transport',icon:'↗'}];
export default function App(){
  const mount=useRef<HTMLDivElement>(null); const [selected,setSelected]=useState<Location|null>(locations[0]); const [query,setQuery]=useState(''); const [category,setCategory]=useState<Category|'ALL'>('ALL'); const [district,setDistrict]=useState('ALL'); const [night,setNight]=useState(false); const [favorites,setFavorites]=useState<string[]>([]); const cityRef=useRef<ReturnType<typeof createCity>|null>(null);
  useEffect(()=>{if(!mount.current)return;const city=createCity((loc)=>{setSelected(loc);city.focus(loc)});cityRef.current=city;mount.current.appendChild(city.renderer.domElement);const resize=()=>{if(!mount.current)return;city.renderer.setSize(mount.current.clientWidth,mount.current.clientHeight,false);city.camera.aspect=mount.current.clientWidth/mount.current.clientHeight;city.camera.updateProjectionMatrix()};resize();window.addEventListener('resize',resize);let raf=0;const animate=()=>{raf=requestAnimationFrame(animate);city.renderer.render(city.scene,city.camera)};animate();return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);city.renderer.dispose();mount.current?.removeChild(city.renderer.domElement)}},[]);
  useEffect(()=>{cityRef.current?.setNight(night)},[night]);
  const visible=useMemo(()=>locations.filter(l=>(category==='ALL'||l.category===category)&&(district==='ALL'||l.district===district)&&(!query||`${l.name} ${l.category} ${l.district}`.toLowerCase().includes(query.toLowerCase()))),[query,category,district]);
  const select=(l:Location)=>{setSelected(l);cityRef.current?.focus(l)}; const toggleFav=()=>{if(!selected)return;setFavorites(f=>f.includes(selected.id)?f.filter(x=>x!==selected.id):[...f,selected.id])};
  return <main className={night?'app night':'app'}><div className="map" ref={mount}/><header className="topbar"><div className="brand"><span className="mark">✦</span><div><strong>SAINT MERIDIAN</strong><small>CITY ATLAS / 04:17 PM</small></div></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the city..."/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-btn" onClick={()=>setNight(!night)} title="Day / night">{night?'☼':'◐'}</button><button className="avatar">JM</button></div></header>
    <aside className="left-rail"><div className="eyebrow">MAP LAYERS</div><button className="layer active"><i className="layer-dot city-dot"/>City <span>ON</span></button><button className="layer"><i className="layer-dot business-dot"/>Businesses <span>{locations.length}</span></button><button className="layer"><i className="layer-dot nightlife-dot"/>Nightlife <span>12</span></button><button className="layer"><i className="layer-dot transport-dot"/>Transport <span>42</span></button><button className="layer"><i className="layer-dot landmark-dot"/>Landmarks <span>18</span></button><div className="rail-rule"/><div className="eyebrow">CITY STATUS</div><div className="status"><span className="live"/>LIVE MODEL <b>0.7</b></div><div className="status"><span className="sun"/>CLEAR / 18°C</div><div className="coords">34° 02′ 18″ N<br/>118° 14′ 02″ W <em>fictional</em></div></aside>
    <section className="filter-panel"><div className="eyebrow">DISCOVER / {visible.length} PLACES</div><div className="chips">{categories.map(c=><button className={category===c.name?'chip selected':''||'chip'} onClick={()=>setCategory(category===c.name?'ALL':c.name)} key={c.name}><span>{c.icon}</span>{c.name}</button>)}</div><select value={district} onChange={e=>setDistrict(e.target.value)}><option value="ALL">All districts</option>{districts.map(d=><option value={d.name} key={d.name}>{d.name}</option>)}</select></section>
    {selected&&<aside className="detail"><div className="detail-head"><span className="type">{selected.category.toUpperCase()}</span><button onClick={()=>setSelected(null)}>×</button></div><div className="detail-title"><h1>{selected.name}</h1><button className={favorites.includes(selected.id)?'heart saved':'heart'} onClick={toggleFav}>♥</button></div><div className="rating"><b>★ {selected.rating}</b><span> / 5.0</span><span className="open">● OPEN NOW</span></div><p>{selected.description}</p><div className="info-row"><span>⌖</span><div><small>ADDRESS</small><strong>{selected.address}</strong></div></div><div className="info-row"><span>◷</span><div><small>HOURS</small><strong>{selected.hours}</strong></div></div><div className="info-row"><span>◈</span><div><small>DISTRICT</small><strong>{selected.district}</strong></div></div><button className="route" onClick={()=>cityRef.current?.focus(selected)}>↗ FLY TO LOCATION</button><div className="nearby"><div className="eyebrow">NEARBY / {locations.filter(l=>l.id!==selected.id).slice(0,3).length}</div>{locations.filter(l=>l.id!==selected.id).slice(0,3).map(l=><button onClick={()=>select(l)} key={l.id}><span className="near-dot" style={{background:l.accent}}/><span>{l.name}<small>{l.category} · {l.district}</small></span><b>›</b></button>)}</div></aside>}
    <div className="controls"><span>DRAG TO ROTATE</span><i/> <span>SCROLL TO ZOOM</span><button onClick={()=>cityRef.current?.focus({x:0,z:0} as Location)}>◎</button></div><div className="scale"><span>0</span><i/><span>500 M</span></div><div className="district-tag"><span className="pulse"/> MERIDIAN CORE <small>SECTOR 04</small></div>
  </main>
}
